### ISSUE TITLE
Porblem starting the project

### ISSUE THREAD

**Issue by GustavoRSSilva** [udacity/FlightSurety#4]
As of right now if you clone the project and try to start the dapp, you get an error.

Step to reproduce:
`git clone git@github.com:udacity/FlightSurety.git`
`cd /to/folder`
`npm i`
`npm run dapp`

The error is:

> > flightsurety@1.0.0 dapp /var/www/FlightSurety
> > webpack-dev-server --mode development --config webpack.config.dapp.js
> 
> internal/modules/cjs/loader.js:550
>     throw err;
>     ^
> 
> Error: Cannot find module 'webpack-cli/bin/config-yargs'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
>     at Module.require (internal/modules/cjs/loader.js:598:17)
>     at require (internal/modules/cjs/helpers.js:11:18)
>     at Object.<anonymous> (/var/www/FlightSurety/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
>     at Module._compile (internal/modules/cjs/loader.js:654:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
>     at Module.load (internal/modules/cjs/loader.js:566:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
> 

Node version: v9.11.2
Npm version: 5.6.0

**Comment by andrescabsi14** [comment]
This problem is fixed by upgrading the version in package.json to:

"webpack-cli": "^3.3.1",
"webpack-dev-server": "3.3.1"
