### ISSUE TITLE
Error when running the npm run dapp

### ISSUE THREAD

**Issue by jamyo9** [udacity/FlightSurety#7]
When executing the "npm run dapp" command I am getting the following error (the "npm install" runs 

> correctly):> webpack-dev-server --mode development --config webpack.config.dapp.js
ℹ ｢wds｣: Project is running at http://localhost:8000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/jamyo9/Desarrollo/Udacity/Project04/dapp
✖ ｢wdm｣:    835 modules
ERROR in ./src/dapp/dom.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jamyo9/Desarrollo/Udacity/Project04/src/dapp/dom.js: Support for the experimental syntax 'classProperties' isn't currently enabled (5:14):
  3 | export default class DOM {
  4 | 
> 5 |     static a = (...args) => DOM.makeElement(`a`, ...args);
    |              ^
  6 |     static button = (...args) => DOM.makeElement(`button`, ...args);
  7 |     static div = (...args) => DOM.makeElement(`div`, ...args);
  8 |     static h1 = (...args) => DOM.makeElement(`h1`, ...args);
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
    at Parser._raise (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:742:17)
    at Parser.raiseWithData (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:735:17)
    at Parser.expectPlugin (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:8762:18)
    at Parser.parseClassProperty (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:12110:12)
    at Parser.pushClassProperty (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:12070:30)
    at Parser.parseClassMemberWithIsStatic (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:12003:14)
    at Parser.parseClassMember (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:11940:10)
    at /Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:11885:14
    at Parser.withTopicForbiddingContext (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:10956:14)
    at Parser.parseClassBody (/Users/jamyo9/Desarrollo/Udacity/Project04/node_modules/@babel/parser/lib/index.js:11862:10)
ℹ ｢wdm｣: Failed to compile.

**Comment by jamyo9** [comment]
I was missing the file .babelrc
